galaxyproject/usegalaxy-playbook

- templates/galaxy/common/static/welcome.html.j2
> fix welcomepage tiny things

- files/galaxy/usegalaxy.org/var/integrated_tool_panel.xml
- files/galaxy/usegalaxy.org/var/shed_tool_conf.xml
Addresses @martenson's concerns on #17
> Add labels and move gemini.

- production/group_vars/galaxyservers.yml
we need more results with more weight on name and section
ping @natefoo @jennaj
> adjust tool panel search config

- templates/galaxy/usegalaxy.org/config/job_conf.xml.j2
add sailfish, weightedaverage and cummerbund
ping @natefoo 
xref: https://github.com/galaxyproject/galaxy/issues/2666
> allocate more 16gb tools

- env/test/group_vars/galaxyservers/vars.yml
@natefoo Mind if I do this?
We may have fixed the issue I was thinking about in the various uwsgi postfork refactoring stuff, since it seems to be working now for other folks per the meeting.  It'd be good to know.
> Re-enable sentry on test

- env/main/group_vars/webservers.yml
and unify the gzip_types with Test
ping @natefoo @dannon
> enable gzipping on main

- env/main/templates/galaxy/config/job_conf.xml.j2
should have similar mem reqs as rna_star
> run star_fusion on bridges

- env/common/group_vars/toolshedwebservers.yml
should resolve galaxyproject/galaxy#2517, suggested by @natefoo
> limit nginx upload size for toolsheds server

- .travis.yml
- env/common/files/galaxy/dynamic_rules/test/unit/job_conf.xml
- env/common/files/galaxy/dynamic_rules/test/unit/job_resource_params_conf.xml
- env/common/files/galaxy/dynamic_rules/test/unit/test_mdw.py
cc @natefoo @jmchilton 
todo:
* dynamically fill actual Main j2 templates for job conf and job resource conf instead of manually generated ones
* tie the galaxy code to the actual galaxy version instead of hardcoding 19.05
* add more tool executions?
passing test: https://travis-ci.org/martenson/usegalaxy-playbook/builds/535921615
> add unit tests for dynamic rule testing and a travis job that runs it

- env/main/group_vars/galaxyservers/vars.yml
- env/test/group_vars/galaxyservers/vars.yml
(10 seconds, from 1s test 3s main)
> Change sloreq reports to catch only the most egregious offenders

- env/test/group_vars/galaxyservers/vars.yml
>  mimic EU tools search boosts 

- env/common/templates/galaxy/static/welcome.html.j2
An untested pull request.  :-(
> Updated JTech scholarship descritpion

- env/common/files/galaxy/dynamic_rules/test/unit/mock_vars.yml
This should fix the test failures
> Add mock var for new pulsar galaxy_url var

- env/main/group_vars/galaxyservers/tools_conf.yml
- env/test/group_vars/galaxyservers/tools_conf.yml
Added ML tools to the list of multicore tools
> Main ML tools now match Test/EU

- env/common/group_vars/tiaasservers/vars.yml
- env/common/stack.yml
- env/main/templates/nginx/usegalaxy.j2
- env/test/templates/nginx/galaxy_test.j2
- requirements.yml
It should remove any remaining EU specific things and make the templates fully customisable.
> Update TIaaS to latest version

- env/common/group_vars/toolshedservers/common_vars.yml
- env/common/stack.yml
- env/common/templates/nginx/toolshed.j2
- env/common/templates/supervisor/toolshed.j2
- env/testtoolshed/group_vars/toolshedservers/vars.yml
- env/testtoolshed/stack_extras.yml
- env/testtoolshed/templates/hgweb/hgweb.py.j2
- env/testtoolshed/templates/systemd/hgweb.service.j2
- env/testtoolshed/templates/systemd/tool_shed.service.j2
- env/toolshed/group_vars/toolshedservers/vars.yml
So we can run 22.05.
@natefoo that's how I deployed it now and it seems to be working.
> Deploy test toolshed under gunicorn

- env/test/files/galaxy/config/panel_views/annotation.yml
- env/test/files/galaxy/config/panel_views/assembly.yml
- env/test/files/galaxy/config/panel_views/cheminformatics.yml
- env/test/files/galaxy/config/panel_views/climate.yml
- env/test/files/galaxy/config/panel_views/cliqseq.yml
- env/test/files/galaxy/config/panel_views/covid19.yml
- env/test/files/galaxy/config/panel_views/ecology.yml
- env/test/files/galaxy/config/panel_views/graphclust.yml
- env/test/files/galaxy/config/panel_views/hicexplorer.yml
- env/test/files/galaxy/config/panel_views/humancellatlas.yml
- env/test/files/galaxy/config/panel_views/imaging.yml
- env/test/files/galaxy/config/panel_views/metabolomics.yml
- env/test/files/galaxy/config/panel_views/metagenomics.yml
- env/test/files/galaxy/config/panel_views/microbiome.yml
- env/test/files/galaxy/config/panel_views/ml.yml
- env/test/files/galaxy/config/panel_views/nanopore.yml
- env/test/files/galaxy/config/panel_views/plants.yml
- env/test/files/galaxy/config/panel_views/proteomics.yml
- env/test/files/galaxy/config/panel_views/rna.yml
- env/test/files/galaxy/config/panel_views/singlecell.yml
- env/test/files/galaxy/config/panel_views/vgp.yml
built using gx-tool-db script @ https://github.com/galaxyproject/gx-tool-db-panel-sync
> add tool panel views to test

- env/main/templates/galaxy/config/job_router_conf.yml.j2
We have now: quay.io/biocontainers/fastx_toolkit:0.0.13--0
> fastx_toolkit container fr version 0.0.13

- env/main/templates/galaxy/config/job_router_conf.yml.j2
This time with samtools working.
> new container with samtools and bedtools

- .gitignore
- env/main/group_vars/all/galaxy_config_vars.yml
Did not run yet, opening for discussion.
> Drop google analytics from primary usegalaxy.org galaxy server

- env/main/group_vars/all/galaxy_config_vars.yml
xref https://github.com/galaxyproject/galaxy/pull/17806 
This will make my GCC screenshots better... and you know might help users and such.
> Make object store language in UI more precise.

- env/common/templates/galaxy/config/tpv/tools.yaml.j2
- env/common/templates/galaxy/config/tpv/tools_vgp.yaml.j2
adding ncbi egapx, copying parameters for batched_lastz from tools.yaml.j2 to tools_vgp.yaml.j2
> adding ncbi egapx, copying parameters for batched_lastz from tools.yaml.j2 to tools_vgp.yaml.j2

- env/common/templates/galaxy/config/tpv/tools.yaml.j2
- env/common/templates/galaxy/config/tpv/tools_vgp.yaml.j2
try giving egapx a full (intead of half) r3.large
> try giving egapx a full r3.large

- env/common/templates/galaxy/config/tpv/tools_vgp.yaml.j2
until we iron out some things we need big sed jobs to progress
> VGP: add big mem to sed,axtchain

- env/main/group_vars/all/galaxy_config_vars.yml
- env/test/group_vars/all/galaxy_config_vars.yml
Tweaks config to a boolean for test, and flips it on for main since it's intermittent on test.  More data points...
> Adjust OIDC config in galaxy configuration (both test and main)
